services:
  1fichier-downloader-frontend:
    image: node
    depends_on:
      - 1fichier-downloader-backend
    container_name: 1fichier-downloader-frontend
    ports:
      - 8080:8080
    env_file: ./.env/frontend.env
    volumes:
      - ./frontend:/workspace
    working_dir: /workspace
    command: sh /workspace/script.sh
    restart: unless-stopped
  1fichier-downloader-backend:
    container_name: 1fichier-downloader-backend
    build: ./backend
    ports:
      - 3030:3030
    env_file: ./.env/backend.env
    volumes:
      - ./backend:/workspace
      - ./backend/download:/downloads # where the files are downloaded
    working_dir: /workspace
    shm_size: "2gb"
    command: python3 src/main.py
    restart: unless-stopped
